import fs from "fs";
import path from "path";

const root = process.cwd();

function readJson(filePath: string) {
  if (!fs.existsSync(filePath)) throw new Error(`Missing file: ${filePath}`);
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function esc(v: any) {
  return String(v ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

const feed = readJson(path.join(root, "exports/article-generator/cms-asset-picker-feed-v0.1.json"));

const cards = feed.selectable_assets.map((a: any) => `
  <div class="card">
    <div class="badge">INTELLIGENCE ASSET</div>
    <h2>${esc(a.display_title)}</h2>
    <p>${esc(a.description)}</p>

    <div class="meta">
      <div><strong>Type</strong><br>${esc(a.asset_type)} / ${esc(a.file_type)}</div>
      <div><strong>Authority</strong><br>${esc(a.authority_score)} / ${esc(a.authority_band)}</div>
      <div><strong>Verification</strong><br>${esc(a.verification_status)}</div>
      <div><strong>CMS policy</strong><br>${esc(a.duplicate_policy)}</div>
    </div>

    <p><strong>Original concept:</strong> ${esc(a.concept_origin.intelligence_question)}</p>
    <p><strong>Related article:</strong> ${esc(a.concept_origin.article_title)}</p>

    <div class="actions">
      <a href="${esc(a.preview_url)}" target="_blank">Open asset</a>
      <button onclick="navigator.clipboard.writeText('${esc(a.source_path)}')">Copy asset path</button>
      <button onclick="navigator.clipboard.writeText('${esc(a.alt_text)}')">Copy alt text</button>
    </div>
  </div>
`).join("");

const html = `<!doctype html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>ZNBW Intelligence Assets</title>
  <style>
    body { margin:0; font-family:Arial,sans-serif; background:#0f172a; color:#e5e7eb; }
    header { background:#020617; padding:30px 42px; border-bottom:1px solid #334155; }
    h1 { margin:0; color:white; }
    main { max-width:1120px; margin:32px auto; padding:0 24px; }
    .card { background:#111827; border:1px solid #334155; border-left:6px solid #14b8a6; border-radius:14px; padding:24px; margin-bottom:22px; }
    .badge { display:inline-block; background:#ccfbf1; color:#115e59; padding:6px 10px; border-radius:999px; font-size:12px; font-weight:700; }
    .meta { display:grid; grid-template-columns:repeat(4,1fr); gap:14px; margin:18px 0; }
    .meta div { background:#0f172a; border:1px solid #334155; border-radius:10px; padding:12px; }
    a, button { display:inline-block; margin-right:10px; background:#12355b; color:white; border:0; padding:10px 14px; border-radius:8px; font-weight:700; text-decoration:none; cursor:pointer; }
    button { background:#0f766e; }
  </style>
</head>
<body>
  <header>
    <h1>ZNBW Intelligence Assets</h1>
    <p>CMS-selectable assets generated by the ZNBW Intelligence Engine. Reuse references; avoid duplicate uploads.</p>
  </header>
  <main>${cards}</main>
</body>
</html>`;

const outDir = path.join(root, "exports/article-generator/intelligence-center");
fs.mkdirSync(outDir, { recursive: true });

const outPath = path.join(outDir, "assets.html");
fs.writeFileSync(outPath, html);

console.log({
  page_version: "intelligence-center-assets-html-v0.1",
  assets: feed.selectable_assets.length,
  output: outPath
});
