import fs from "fs";
import path from "path";

const root = process.cwd();

function readJson(filePath: string) {
  if (!fs.existsSync(filePath)) throw new Error(`Missing file: ${filePath}`);
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

const cms = readJson(path.join(root, "exports/article-generator/cms-finalization-package-v0.1.json"));
const gate = readJson(path.join(root, "exports/article-generator/publication-readiness-gate-v0.1.json"));
const authority = readJson(path.join(root, "exports/article-generator/publication-source-authority-review-v0.1.json"));
const evidence = readJson(path.join(root, "exports/article-generator/article-evidence-strength-review-v0.1.json"));
const graph = readJson(path.join(root, "exports/article-generator/institutional-graph-package-v0.1.json"));

const payload = cms.article_payload;

const registry = {
  registry_version: "candidate-article-registry-v0.1",
  generated_at: new Date().toISOString(),
  source_system: "ZNBW_Intelligence_Engine",
  purpose:
    "Registry of pre-draft article candidates generated by the Intelligence Engine before manual CMS promotion.",
  candidates: [
    {
      candidate_id: "CAND_0001",
      title: payload.title,
      slug: payload.slug,
      country: payload.country,
      category: payload.category,
      excerpt:
        "Petroleum output provides a useful lens into Singapore's exposure to global energy cycles. Sector-level manufacturing data shows a mixed industrial picture, with petroleum, transport engineering, chemicals, and total manufacturing moving in different directions.",
      status: "ready_for_editorial_review",
      publication_grade: payload.publication_grade,
      institutional_grade: gate.decision?.institutional_grade === true,
      publish_allowed: gate.decision?.publish_allowed === true,
      authority_score: authority.scores?.authority_score ?? null,
      authority_band: authority.band ?? null,
      evidence_score: evidence.scores?.overall_publication_strength_score ?? null,
      evidence_band: evidence.bands?.overall ?? null,
      graph_ready: graph.graph_ready === true,
      asset_ids: ["GRAPH_0001"],
      preview: {
        available: true,
        relative_path:
          "exports/article-generator/previews/what-petroleum-output-reveals-about-singapore-s-exposure-to-global-energy-cycles-preview-v0.1.html",
        admin_note:
          "Preview currently generated as static HTML. Native Admin preview will be added later."
      },
      cms: {
        promotion_status: "not_promoted",
        promotion_allowed: false,
        promotion_note:
          "Manual copy/paste into CMS for phase one. Automated draft creation will be added later."
      },
      governance: {
        human_review_required: true,
        publication_blocked_from_intelligence_center: true,
        source_trace_required: true,
        assets_must_be_reviewed_before_cms_use: true
      }
    }
  ]
};

const outPath = path.join(root, "exports/article-generator/candidate-article-registry-v0.1.json");
fs.writeFileSync(outPath, JSON.stringify(registry, null, 2));

console.log({
  registry_version: registry.registry_version,
  candidates: registry.candidates.length,
  output: outPath
});
