import { Link } from "react-router-dom";

export default function IntelligenceCenter() {
  return (
    <div className="cms-page">
      <div className="cms-page-header">
        <div>
          <p className="cms-eyebrow">ZNBW Intelligence Engine</p>
          <h1>Intelligence Center</h1>
          <p>
            Review Intelligence Engine pre-draft articles before manual promotion
            into the CMS. This area is separated from published articles.
          </p>
        </div>
      </div>

      <div style={{ display: "grid", gap: 16 }}>
        <Link className="cms-card" to="/intelligence-candidates">
          <p className="cms-kicker">Editorial Review</p>
          <h2>Pre-Draft Articles</h2>
          <p>
            Review candidate articles generated by the Intelligence Engine before
            deciding whether they should become CMS drafts.
          </p>
        </Link>
      </div>
    </div>
  );
}
